[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "9.15.1"
  NX_SKIP_NX_CACHE = "true"

[build]
  base = "/"
  command = "pnpm install && pnpm nx build demo"
  publish = "dist/apps/demo"